#!/bin/bash

# AI Chatbot Leads - Quick Deploy Script
echo "🚀 AI Chatbot Leads Deployment Helper"
echo "====================================="

echo ""
echo "📋 Your project is ready for deployment!"
echo ""
echo "🌐 GitHub Repository: https://github.com/swastik-21/ai-chatbot-leads"
echo ""
echo "💰 Recommended Deployment Options:"
echo ""
echo "1. 🆓 RENDER (FREE TIER) - Recommended for starting"
echo "   • Go to: https://render.com"
echo "   • Sign up and connect GitHub"
echo "   • Deploy from: https://github.com/swastik-21/ai-chatbot-leads"
echo "   • Use the render.yaml config file"
echo ""
echo "2. 💵 RAILWAY ($5/month) - Best value for production"
echo "   • Go to: https://railway.app"
echo "   • Sign up and connect GitHub"
echo "   • Deploy from: https://github.com/swastik-21/ai-chatbot-leads"
echo "   • Use the railway.toml config file"
echo ""
echo "🔑 Required Environment Variables:"
echo "   • OPENAI_API_KEY: Your OpenAI API key"
echo "   • DJANGO_SECRET_KEY: Generate with: python -c 'import secrets; print(secrets.token_urlsafe(50))'"
echo "   • DEBUG: False"
echo "   • ALLOWED_HOSTS: *"
echo ""
echo "📖 Full deployment guide: DEPLOYMENT.md"
echo ""
echo "✅ Your project is production-ready!"
echo "   • Fixed OpenAI compatibility issues"
echo "   • Optimized for cost-effective hosting"
echo "   • Includes comprehensive deployment configs"
echo "   • Ready for immediate deployment"


