# Railway deployment configuration
[build]
builder = "dockerfile"

[deploy]
startCommand = "gunicorn ai_chatbot_leads.wsgi:application --bind 0.0.0.0:$PORT --timeout 120 --workers 1"

[env]
OPENAI_API_KEY = "required"
DJANGO_SECRET_KEY = "required"
DEBUG = "False"
ALLOWED_HOSTS = "*"




