# Railway deployment configuration
[build]
builder = "dockerfile"

[deploy]
startCommand = "./start.sh"

[env]
OPENAI_API_KEY = "required"
DJANGO_SECRET_KEY = "required"
DEBUG = "False"
ALLOWED_HOSTS = "*"
PORT = "8000"




