# Railway deployment configuration
[build]
builder = "dockerfile"

[deploy]
startCommand = "python manage.py migrate && python manage.py seed_faqs && gunicorn ai_chatbot_leads.wsgi:application --bind 0.0.0.0:8000 --timeout 120 --workers 1"

[env]
OPENAI_API_KEY = "required"
DJANGO_SECRET_KEY = "required"
DEBUG = "False"
ALLOWED_HOSTS = "*"




